repos:
-   repo: local
    hooks:
    -   id: go-fmt
        name: go fmt
        entry: go fmt
        language: system
        types: [go]
    -   id: go-test
        name: go test
        entry: make test
        language: system
        types: [go]
        pass_filenames: false
    -   id: go-benchmark
        name: go benchmark
        description: Run benchmarks and save results
        entry: make benchmark-save
        language: system
        types: [go]
        pass_filenames: false
    -   id: benchstat
        name: benchstat comparison
        description: Compare benchmark results with previous run
        entry: bash -c 'if [ -f benchstat/previous.txt ]; then make benchmark-compare && cp benchstat/latest.txt benchstat/previous.txt; else make benchmark-save-as-previous && echo "First benchmark run - results stored for future comparison."; fi'
        language: system
        types: [go]
        pass_filenames: false
        verbose: true 