- name: test playbook
  hosts: localhost
  vars:
    var1: 123
    var2: 234
  tasks:
    - name: nested vars
      debug:
        msg: "var1 {{ var1 }} and var2 {{ var2 }}"
    - name: nested vars
      debug:
        msg: "var1 {{ var1 }} and var2 {{ {{ var2 }} }}"
